Fix cname contents being optional
theforeman/puppet-certs pull request #309
Opened 2020-12-22 14:55 UTC by ehelms

Fixes the following error during validation:

Parameter certs-cname invalid: Elements of the array are invalid: [] must match one of
(?-mix:\A(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9])\z

2020-12-22 15:09 UTC, wbclark approved these changes
ACK

2020-12-22 15:50 UTC, ekohl requested changes
This looks wrong to me. It indicates some invalid value is being passed in. I think I've seen Kafo interpret some values literally. It may be passing in `'[]'` instead of `[]`.

What this says is that `[undef]` is a value entry, which it isn't.

2020-12-22 15:57 UTC, ehelms commented
Hrmm, I wonder if the parser cache is not getting re-created locally for me and it's using the old value which was a string.

2020-12-22 16:08 UTC, ekohl commented
I think I've seen this problem before. In 3beda1df35481210b581f9beeb63d1dcafd2aca0 I reverted the same thing for the same reason. The root cause is that puppet-strings extracts the Puppet literal and doesn't expose a data typed entry. Kafo can't find out it's actually an empty array and assumes it's a literal string.

2020-12-22 19:32 UTC, ekohl commented
The output of `bundle exec puppet strings generate --format json manifests/init.pp`:
```json
{
  "puppet_classes": [
    {
      "name": "certs",
      "file": "manifests/init.pp",
      "line": 70,
      "inherits": "certs::params",
      "docstring": {
        "text": "== Class: certs\n\nBase for installing and configuring certs. It holds the basic configuration\naournd certificates generation and deployment. The per-subsystem configuratoin\nof certificates should go into `subsystem_module/manifests/certs.pp`.\n\n=== Parameters:\n\n$node_fqdn::            The fqdn of the host the generated certificates\n                        should be for\n\n$cname::                The alternative names of the host the generated certificates\n                        should be for\n\n$server_ca_cert::       Path to the CA that issued the ssl certificates for https\n                        if not specified, the default CA will be used\n\n$server_cert::          Path to the ssl certificate for https\n                        if not specified, the default CA will generate one\n\n$server_key::           Path to the ssl key for https\n                        if not specified, the default CA will generate one\n\n$server_cert_req::      Path to the ssl certificate request for https\n                        if not specified, the default CA will generate one\n\n$tar_file::             Use a tarball with certificates rather than generate\n                        new ones. This can be used on another node which is\n                        not the CA.\n\n=== Advanced parameters:\n\n$generate::             Should the generation of the certs be part of the\n                        configuration\n\n$regenerate::           Force regeneration of the certificates (excluding\n                        CA certificates)\n\n$deploy::               Deploy the certs on the configured system. False means\n                        we want to apply it to a different system\n\n$ca_common_name::       Common name for the generated CA certificate\n\n$country::              Country attribute for managed certificates\n\n$state::                State attribute for managed certificates\n\n$city::                 City attribute for managed certificates\n\n$org::                  Org attribute for managed certificates\n\n$org_unit::             Org unit attribute for managed certificates\n\n$expiration::           Expiration attribute for managed certificates\n\n$ca_expiration::        CA expiration attribute for managed certificates\n\n$pki_dir::              The PKI directory under which to place certs\n\n$ssl_build_dir::        The directory where SSL keys, certs and RPMs will be generated\n\n$user::                 The system user name who should own the certs\n\n$group::                The group who should own the certs\n\n$default_ca_name::      The name of the default CA\n\n$server_ca_name::       The name of the server CA (used for https)",
        "tags": [
          {
            "tag_name": "param",
            "text": "",
            "types": [
              "Stdlib::Fqdn"
            ],
            "name": "node_fqdn"
          },
          {
            "tag_name": "param",
            "text": "",
            "types": [
              "Array[Stdlib::Fqdn]"
            ],
            "name": "cname"
          },
          {
            "tag_name": "param",
            "text": "",
            "types": [
              "Boolean"
            ],
            "name": "generate"
          },
          {
            "tag_name": "param",
            "text": "",
            "types": [
              "Boolean"
            ],
            "name": "regenerate"
          },
          {
            "tag_name": "param",
            "text": "",
            "types": [
              "Boolean"
            ],
            "name": "deploy"
          },
          {
            "tag_name": "param",
            "text": "",
            "types": [
              "String"
            ],
            "name": "ca_common_name"
          },
          {
            "tag_name": "param",
            "text": "",
            "types": [
              "String[2,2]"
            ],
            "name": "country"
          },
          {
            "tag_name": "param",
            "text": "",
            "types": [
              "String"
            ],
            "name": "state"
          },
          {
            "tag_name": "param",
            "text": "",
            "types": [
              "String"
            ],
            "name": "city"
          },
          {
            "tag_name": "param",
            "text": "",
            "types": [
              "String"
            ],
            "name": "org"
          },
          {
            "tag_name": "param",
            "text": "",
            "types": [
              "String"
            ],
            "name": "org_unit"
          },
          {
            "tag_name": "param",
            "text": "",
            "types": [
              "String"
            ],
            "name": "expiration"
          },
          {
            "tag_name": "param",
            "text": "",
            "types": [
              "String"
            ],
            "name": "ca_expiration"
          },
          {
            "tag_name": "param",
            "text": "",
            "types": [
              "Optional[Stdlib::Absolutepath]"
            ],
            "name": "server_cert"
          },
          {
            "tag_name": "param",
            "text": "",
            "types": [
              "Optional[Stdlib::Absolutepath]"
            ],
            "name": "server_key"
          },
          {
            "tag_name": "param",
            "text": "",
            "types": [
              "Optional[Stdlib::Absolutepath]"
            ],
            "name": "server_cert_req"
          },
          {
            "tag_name": "param",
            "text": "",
            "types": [
              "Optional[Stdlib::Absolutepath]"
            ],
            "name": "server_ca_cert"
          },
          {
            "tag_name": "param",
            "text": "",
            "types": [
              "Stdlib::Absolutepath"
            ],
            "name": "pki_dir"
          },
          {
            "tag_name": "param",
            "text": "",
            "types": [
              "Stdlib::Absolutepath"
            ],
            "name": "ssl_build_dir"
          },
          {
            "tag_name": "param",
            "text": "",
            "types": [
              "String"
            ],
            "name": "user"
          },
          {
            "tag_name": "param",
            "text": "",
            "types": [
              "String"
            ],
            "name": "group"
          },
          {
            "tag_name": "param",
            "text": "",
            "types": [
              "String"
            ],
            "name": "default_ca_name"
          },
          {
            "tag_name": "param",
            "text": "",
            "types": [
              "String"
            ],
            "name": "server_ca_name"
          },
          {
            "tag_name": "param",
            "text": "",
            "types": [
              "Optional[Stdlib::Absolutepath]"
            ],
            "name": "tar_file"
          }
        ]
      },
      "defaults": {
        "node_fqdn": "$certs::params::node_fqdn",
        "cname": "[]",
        "generate": "true",
        "regenerate": "false",
        "deploy": "true",
        "ca_common_name": "$certs::params::ca_common_name",
        "country": "'US'",
        "state": "'North Carolina'",
        "city": "'Raleigh'",
        "org": "'Katello'",
        "org_unit": "'SomeOrgUnit'",
        "expiration": "'7300'",
        "ca_expiration": "'36500'",
        "server_cert": "undef",
        "server_key": "undef",
        "server_cert_req": "undef",
        "server_ca_cert": "undef",
        "pki_dir": "$certs::params::pki_ [...]

2021-01-04 13:27 UTC, ehelms commented
@ekohl @wbclark I went a revert to params.pp route to fix this for the time being and unblock nightly

2021-01-04 13:29 UTC, ekohl approved these changes
Thanks for filing an issue as well.

2021-01-04 13:37 UTC, merged